title: Yaser Marey Blog
description: Yaser Marey Blog
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  yasseronline ( migration is going on! ): https://yasseronline.wordpress.com
