title: Yaser Marey Blog
description: Yaser Marey Blog
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  yasseronline ( migration is going on! ): https://yasseronline.wordpress.com

enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html